- hosts: all
  become: true
  tasks:
    - name: install apache and php
      package:
        name:
          - { { appache_package } }
          - { { php_package } }
        state: latest
        update_cache: yes
